
vaadin:
  launch-browser: true
  push:
    enabled: true

spring:
  application:
    name: inc-display

broadcaster-config:
  default-display: ---
  use-key-when-not-present: true
  short-codes:
    0: DOXOLOGY
    888: Pasalamat
    999: INC
client-config:
  timeout: 10000
  display-clients:
    - name: Left
      icon: CHEVRON_CIRCLE_LEFT
      ip: 192.168.0.40
      port: 22
      host: pi02l.local
      username: pi
      password: pi
    - name: Right
      icon: CHEVRON_CIRCLE_RIGHT
      ip: 192.168.0.41
      port: 22
      host: pi02r.local
      username: pi
      password: pi
    - name: Center
      icon: CHEVRON_CIRCLE_UP
      ip: 192.168.0.39
      port: 22
      host: pi02c.local
      username: pi
      password: pi
app-settings:
  default-theme: dark